version: "3.9"

services:
  backend:
    build: ./backend
    container_name: fastapi-app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql+asyncpg://admin:admin@db:5432/taskdb
    volumes:
      - ./backend:/app
    depends_on:
      - db

  frontend:
    build: ./frontend/app-frontend
    container_name: angular-app
    ports:
      - "4200:80"
    depends_on:
      - backend

  db:
    image: postgres:15
    container_name: postgres-db
    environment:
      - POSTGRES_DB=taskdb
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    ports:
      - "5432:5432"
    volumes:
    - pgdata:/var/lib/postgresql/data
    - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro

volumes:
  pgdata:
